### ISSUE TITLE
sound options not working in main menu

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#130]

**Comment by BlackFuse** [comment]
Fixed

**Comment by NAT0P0TAT0** [comment]
works in level pause menus but the options are unmovable in the main menu

**Comment by NAT0P0TAT0** [comment]
still cant move the volume sliders with a mouse in the main menu, in editor or build
