### ISSUE TITLE
PRE TESTING - Game finish screen

### ISSUE THREAD

**Issue by NAT0P0TAT0** [thommoboy/There-are-no-brakes#34]
Basically instead of "Time remaining" it should be "Total Time spent"    

and instead of "levels completed" it should be the time spent in each level eg:
"level 1 time: 00:00"
"level 2 time: 00:00"
"level 3 time: 00:00"  
(dont count tutorial)

**Comment by NAT0P0TAT0** [comment]
I've set the HUD script to save level times as PlayerPref floats, you should be able to easily access them with:
PlayerPrefs.GetFloat("Level1Time");
PlayerPrefs.GetFloat("Level2Time");
PlayerPrefs.GetFloat("Level3Time");

**Comment by BlackFuse** [comment]
Done, thanks suggestion.

**Comment by NAT0P0TAT0** [comment]
Does not show level 3 time, still uses default values for total game time and 'rating'

**Comment by NAT0P0TAT0** [comment]
doesn't show level 3 time (level 3 thing not showing is a cropping issue, it appeared when total time was commented out), rating system doesnt work, if its not fixed soon we'll probably just skip/comment it

**Comment by NAT0P0TAT0** [comment]
for now we've taken out the game rating and total time, just so it can work for playtesting
